// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutText from '@/components/sections/about/AboutText';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutText
          title="Diseño web enfocado en resultados locales en Costa Rica. Con años de experiencia ayudando a emprendedores, transformo ideas en plataformas digitales que convierten visitantes en clientes fieles."
        />
        </SectionErrorBoundary>
      </div>
  );
}
