// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutText from '@/components/sections/about/AboutText';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutText
          title='¿Tenés un buen negocio pero en internet nadie te encuentra?
Eso tiene solución. Creo páginas web para que las personas que ya están buscando lo que vos ofrecés, te encuentren a vos primero — y elijan llamarte a vos.'
        />
        </SectionErrorBoundary>
      </div>
  );
}
