// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="¡Hablemos ahora!"
          text="Todo esto en español. Escríbeme y empecemos hoy mismo."
          primaryButton={{
            text: "💬 Escribir por WhatsApp",
            href: "https://wa.me/50664264652?text=Hola%20quiero%20informacion%20sobre%20la%20pagina%20web",
          }}
          secondaryButton={{
            text: "Ver trabajos",
            href: "#features",
          }}
        />
        </SectionErrorBoundary>
      </div>
  );
}
