// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTabbedAccordion from '@/components/sections/faq/FaqTabbedAccordion';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTabbedAccordion
          tag="Preguntas Frecuentes"
          title="Todo lo que necesitas saber"
          description="Resolvemos tus dudas sobre el proceso de creación web."
          categories={[
            {
              name: "Proceso",
              items: [
                {
                  question: "¿Cuánto tarda la entrega?",
                  answer: "Entrego proyectos completos en 7 días hábiles.",
                },
                {
                  question: "¿Incluye soporte?",
                  answer: "Sí, incluyo soporte técnico durante el primer mes.",
                },
              ],
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
