// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
        <SectionErrorBoundary name="features">
              <FeaturesRevealCardsBento
          tag="Soluciones Digitales"
          title="Servicios que impulsan tu negocio"
          description="Herramientas diseñadas para escalar tu presencia en línea."
          items={[
            {
              title: "Diseño Moderno",
              description: "Interfaces limpias, atractivas y responsive.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/fast-time-clock-ui-icon-sign-symbol-3d-rendering_56104-1926.jpg",
            },
            {
              title: "Velocidad Extrema",
              description: "Páginas optimizadas para cargar en milisegundos.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/fast-speed-broadband-accelerate-internet_53876-133585.jpg",
            },
            {
              title: "SEO Local",
              description: "Posicionamiento efectivo en Costa Rica.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/hands-holding-up-colorful-letters-forming-abbreviation-seo_53876-167038.jpg",
            },
            {
              title: "Conversión",
              description: "Diseños estratégicos para vender más.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/arrangement-with-colorful-shapes_23-2148879428.jpg",
            },
            {
              title: "Soporte Total",
              description: "Acompañamiento continuo post-entrega.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/call-center-agent-talking-headset-mic-typing-keyboard_482257-125066.jpg",
            },
            {
              title: "Integración",
              description: "Conexión directa con WhatsApp y CRM.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/chat-conversation-communication-connection-concept_53876-124388.jpg",
            },
            {
              title: "Entrega Rápida",
              description: "Tu página lista en tan solo 7 días.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-vector/pack-various-fast-service-logo-designs_52683-61830.jpg",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
