// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBillboardTiltedCarousel from '@/components/sections/hero/HeroBillboardTiltedCarousel';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroBillboardTiltedCarousel
          tag=""
          title="Tu negocio merece una página que vende"
          description="Creo páginas web modernas para negocios locales en Costa Rica. Rápidas, profesionales y diseñadas para atraer más clientes."
          primaryButton={{
            text: "💬 Escribir por WhatsApp",
            href: "https://wa.me/50664264652?text=Hola%20quiero%20informacion%20sobre%20la%20pagina%20web",
          }}
          secondaryButton={{
            text: "Ver mis trabajos →",
            href: "#features",
          }}
          items={[
            {
              imageSrc: "http://img.b2bpic.net/free-photo/office-work-computer-technology-concept_53876-133883.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/3d-rendering-website-hosting-concept_23-2149484781.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/diverse-secret-agents-examine-clues-cia-secret-base-with-green-screen_482257-119889.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-vector/gradient-ui-ux-elements_23-2149061049.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/man-switching-bulbs-using-voice-command-tablet_482257-8730.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-vector/gradient-colored-ui-kit-collection_23-2149209070.jpg",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
