/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import GridOrCarousel from "@/components/ui/GridOrCarousel";
import ScrollReveal from "@/components/ui/ScrollReveal";
import ImageOrVideo from "@/components/ui/ImageOrVideo";

const metrics = [
  {
    value: "+85%",
    description: "Aumento en tasa de conversión",
    imageSrc: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80"
  },
  {
    value: "7 Días",
    description: "Tiempo promedio de entrega",
    imageSrc: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&q=80"
  },
  {
    value: "100%",
    description: "Diseños personalizados",
    imageSrc: "https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&q=80"
  }
];

type Metric = {
  value: string;
  description: string;
  imageSrc?: string;
};

const MetricsInline = () => (
  <section aria-label="Metrics section" className="py-20">
    <div className="flex flex-col gap-8 md:gap-10">
      <div className="flex flex-col items-center gap-2 w-content-width mx-auto">
        <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
          <p>{"Impacto Medible"}</p>
        </div>

        <TextAnimation
          text={"Resultados concretos"}
          variant="fade-blur"
          gradientText={true}
          tag="h2"
          className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
        />

        <TextAnimation
          text={"Elevamos los estándares de tu presencia digital."}
          variant="fade-blur"
          gradientText={false}
          tag="p"
          className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
        />

        {(undefined || undefined) && (
          <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
            {undefined && <Button text={undefined.text} href={undefined.href} variant="primary"/>}
            {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary"animationDelay={0.1} />}
          </div>
        )}
      </div>

      <ScrollReveal variant="slide-up">
        <GridOrCarousel>
          {metrics.map((metric) => (
            <div key={metric.value} className="flex flex-col justify-between gap-6 p-6 md:p-10 min-h-60 md:min-h-70 2xl:min-h-80 h-full card rounded relative overflow-hidden group">
              {metric.imageSrc && (
                <div className="absolute inset-0 z-0">
                  <ImageOrVideo imageSrc={metric.imageSrc} className="w-full h-full object-cover opacity-40 group-hover:opacity-60 transition-opacity duration-500" />
                  <div className="absolute inset-0 bg-gradient-to-t from-card via-card/60 to-transparent"></div>
                </div>
              )}
              <div className="relative z-10 flex flex-col justify-between h-full">
                <span className="text-9xl md:text-8xl font-semibold leading-none truncate">{metric.value}</span>
                <p className="text-base leading-snug text-balance">{metric.description}</p>
              </div>
            </div>
          ))}
        </GridOrCarousel>
      </ScrollReveal>
    </div>
  </section>
);

export default function MetricsSection() {
  return (
    <div data-webild-section="metrics" id="metrics">
      <MetricsInline />
    </div>
  );
}
