// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialColumnMarqueeCards from '@/components/sections/testimonial/TestimonialColumnMarqueeCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialColumnMarqueeCards
          tag="Clientes Satisfechos"
          title="Lo que dicen de mi trabajo"
          description="Testimonios reales de emprendedores en Costa Rica."
          testimonials={[
            {
              name: "Sofía Vargas",
              role: "Propietaria, Salón de Belleza",
              quote: "Excelente trabajo, mi sitio ahora vende solo.",
              imageSrc: "http://img.b2bpic.net/free-photo/serious-executive-with-short-hair-crossed-arms_1149-89.jpg",
            },
            {
              name: "Carlos Mora",
              role: "Fundador, StartUp Tech",
              quote: "La entrega fue puntual y de alta calidad.",
              imageSrc: "http://img.b2bpic.net/free-photo/happy-confident-bearded-man-brown-suit-wearing-glasses-looking-camera-smiling-cheerfully-with-arms-crossed-standing-purple-background_141793-110713.jpg",
            },
            {
              name: "Elena Torres",
              role: "Gerente, Boutique",
              quote: "Kevin entendió perfectamente la marca.",
              imageSrc: "http://img.b2bpic.net/free-photo/business-woman-banner-concept-with-copy-space_23-2149601533.jpg",
            },
            {
              name: "Javier Solís",
              role: "Restaurador",
              quote: "El sitio es muy rápido y fácil de manejar.",
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-bearded-man-holding-his-arms-crossed_23-2148737964.jpg",
            },
            {
              name: "Ana Castro",
              role: "Consultora",
              quote: "Profesionalismo de principio a fin.",
              imageSrc: "http://img.b2bpic.net/free-photo/blond-business-woman-blue-shirt_23-2148095792.jpg",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
